/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as EdicoesRouteImport } from './routes/edicoes'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as AtrativosRouteImport } from './routes/atrativos'
import { Route as IndexRouteImport } from './routes/index'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const EdicoesRoute = EdicoesRouteImport.update({
  id: '/edicoes',
  path: '/edicoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const AtrativosRoute = AtrativosRouteImport.update({
  id: '/atrativos',
  path: '/atrativos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atrativos': typeof AtrativosRoute
  '/contato': typeof ContatoRoute
  '/edicoes': typeof EdicoesRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atrativos': typeof AtrativosRoute
  '/contato': typeof ContatoRoute
  '/edicoes': typeof EdicoesRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atrativos': typeof AtrativosRoute
  '/contato': typeof ContatoRoute
  '/edicoes': typeof EdicoesRoute
  '/sobre': typeof SobreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/atrativos' | '/contato' | '/edicoes' | '/sobre'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/atrativos' | '/contato' | '/edicoes' | '/sobre'
  id: '__root__' | '/' | '/atrativos' | '/contato' | '/edicoes' | '/sobre'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtrativosRoute: typeof AtrativosRoute
  ContatoRoute: typeof ContatoRoute
  EdicoesRoute: typeof EdicoesRoute
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edicoes': {
      id: '/edicoes'
      path: '/edicoes'
      fullPath: '/edicoes'
      preLoaderRoute: typeof EdicoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atrativos': {
      id: '/atrativos'
      path: '/atrativos'
      fullPath: '/atrativos'
      preLoaderRoute: typeof AtrativosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtrativosRoute: AtrativosRoute,
  ContatoRoute: ContatoRoute,
  EdicoesRoute: EdicoesRoute,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
